### ISSUE TITLE
Extraction not Perfect

### ISSUE THREAD

**Issue by joesinghh** [joesinghh/Text-Extractor#1]
Extraction of the captured image is not perfect, hardly any output is generated.
Any PR fixing this issue will be appreciated.

**Comment by Prajwalprakash3722** [comment]
@Joe-Sin7h  can I take the PR, I have quite understood your problem.

**Comment by joesinghh** [comment]
@Prajwalprakash3722  yes, please feel free to make a PR fixing this bug.
