### ISSUE TITLE
About Tinker

### ISSUE THREAD

**Issue by Prajwalprakash3722** [joesinghh/Text-Extractor#4]
Why not change the tinker GUI to stream-lit web app, it is more has more look, and even has a drag and drop folder for image reading. 

Let me know your thoughts.. 

@Joe-Sin7h

**Comment by joesinghh** [comment]
Yeah, stream lit is definitely a good choice. Please go ahead with the idea and try working on it.

**Comment by Prajwalprakash3722** [comment]
Yes @Joe-Sin7h

**Comment by Prajwalprakash3722** [comment]
assign it to me
